Theodo\RogerCmsBundle\Entity\Page:
    type: entity
    table: roger_cms_page
    repositoryClass: Theodo\RogerCmsBundle\Repository\PageRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        content:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
            unique: true
        breadcrumb:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        keywords:
            type: text
            nullable: true
        status:
            type: string
            length: 127
        parentId:
            type: integer
            nullable: true
        contentType:
            type: string
            length: 127
        cacheable:
            type: boolean
        public:
            type: boolean
        lifetime:
            type: integer
            nullable: true
        publishedAt:
            type: date
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        parent:
            targetEntity: Page
            inversedBy: children
            joinColumn:
                name: parentId
                referencedColumnName: id
    oneToMany:
        children:
            targetEntity: Page
            mappedBy: parent
            cascade: ["remove"]
